### ISSUE TITLE
SSProgressView.h missing

### ISSUE THREAD

**Issue by Ged2323** [zeroCoder1/iOS-Audio-Metering-Visualiser#1]
Hi I tried to run this but some files are missing
- SSProgressView.h and .m

**Comment by zeroCoder1** [comment]
I am sorry about that. There is no need of that dependency, you can just remove that, and add a sound file. It should work without any hiccups. 
It's my carelessness, I committed without seeing the code. 
PS: if you want to look at the SSProgressView, then that lies here
https://github.com/zeroCoder1/Progress-Bar
But it has no use here.

**Comment by Ged2323** [comment]
Ok thanks 
I also had to turn off bitcode in build settings.

**Comment by zeroCoder1** [comment]
Yup its an old project, I try and keep up with the new iOS versions when I can.

**Comment by Ged2323** [comment]
Thanks mate it's a great project. Just wondering do you know how to capture the out put sound of the speakers. Just say you are playing a music file from the music app that comes along with the iPhone is there any way of getting the app to track and visualise that sound that is being played?
Regards Gerard

**Comment by zeroCoder1** [comment]
Instead, why not make a music app that leverages MPMusicPlayerController? Rest I need to figure out.
